Smack: Repair netfilter dependency
On 1/23/2015 8:20 AM, Jim Davis wrote:
> Building with the attached random configuration file,
>
> security/smack/smack_netfilter.c: In function ‘smack_ipv4_output’:
> security/smack/smack_netfilter.c:55:6: error: ‘struct sk_buff’ has no
> member named ‘secmark’
>    skb->secmark = skp->smk_secid;
>       ^
> make[2]: *** [security/smack/smack_netfilter.o] Error 1

The existing Makefile used the wrong configuration option to
determine if smack_netfilter should be built. This sets it right.

Resolves: Jira:LXSWI9X1517-123
Signed-off-by: Casey Schaufler <casey@schaufler-ca.com>
(cherry picked from commit 82b0b2c2b1e64ad6c5309a9eeba806af9812666b)
Signed-off-by: Dragan Marinkovic <dmarinkovi@sierrawireless.com>

Change-Id: I6524bc69bc757d247e7c5d3fe5c71b813b7c16db